services:
  mongodb:
<<<<<<< HEAD
    image: mongo:latest  # Utilisation de l'image officielle MongoDB
=======
    image: mongo:latest  # Utilise l'image officielle de MongoDB
>>>>>>> dev
    container_name: mongodb_new
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
<<<<<<< HEAD
    image: ed1109/reverse_todo-backend:latest  # Nom de l'image avec votre Docker Hub username
=======
    image: ed1109/backend:latest  # Définit l'image à pousser sur Docker Hub
>>>>>>> dev
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/reverse_todo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3001
<<<<<<< HEAD
    image: ed1109/reverse_todo-frontend:latest  # Nom de l'image avec votre Docker Hub username
=======
    image: ed1109/frontend:latest  # Définit l'image à pousser sur Docker Hub
>>>>>>> dev
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
