name: CI/CD Workflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  # Job: Merge feature branches into dev
  build-and-merge-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test

      - name: Merge dev to staging
        uses: pascalgn/automerge-action@v0.15.3
        with:
          target_branch: staging
          merge_method: merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job: Merge dev into main and build Docker images
  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test

      - name: Build Docker Images
        run: docker-compose build

      - name: Push Docker Images to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose push
